---
pagetitle: "MMA, Ph.D., Contact"
---

<style type="text/css">
span.ltrText {unicode-bidi: bidi-override; direction: rtl}
</style>

<br />
<br />
<br />

```{r setup, include=F}
knitr::opts_chunk$set(echo = F)
```

<br />
<br />
<br />
<br />

```{r}
icons::fontawesome$solid$envelope
```
<span class="ltrText">ten.gadratarumm
```{r}
icons::fontawesome$solid$at
```
amm</span>

<br />

[
```{r}
icons::academicons$`google-scholar`
```
](https://scholar.google.com/citations?user=6MoKqzkAAAAJ&hl=en){target="_blank"}

[
```{r}
icons::academicons$orcid
```
](https://orcid.org/0000-0001-9111-1088){target="_blank"}

[
```{r}
icons::academicons$osf
```
](https://osf.io/4dvtj/){target="_blank"}

[
```{r}
icons::academicons$researchgate
```
](https://www.researchgate.net/profile/M_Ardag){target="_blank"}

[
```{r}
icons::academicons$publons
```
](https://publons.com/researcher/3623074/m-murat-ardag/){target="_blank"}

[
```{r}
icons::fontawesome$brands$github
```
](https://github.com/mmuratardag){target="_blank"} 

<div>
GDPR & LEGAL DISCLAIMER
<br>
The new General Data Protection Regulation (GDPR), May 25 2018, requires a data transparency statement. This site is made with R Markdown and hosted on GitHub. Read [this](https://docs.github.com/en/github/site-policy/github-terms-of-service){target="_blank"} to have an idea about what GitHub's ToS are. I use no plugins or back-end software to collect visitor data.
</div>